[env:ch552g]
platform = intel_mcs51
board = ch552g
build_flags =
  -DCH552
  -DF_CPU=16000000L
  -DF_EXT_OSC=0L
  -DUSER_USB_RAM=148
  -Ddouble=float
  -DUSE_STDINT
  -D__PROG_TYPES_COMPAT__
  --int-long-reent
  --xram-size 876
  --xram-loc 148
extra_scripts = post:scripts/upload_ch552.py
upload_port = COM42
